import fs from 'node:fs/promises'
import path from 'node:path'
import type { Phase1Output, Phase2Output, Observation } from './pipeline2.js'

export type Report2Meta = {
  start: Date
  end: Date
  sessionCount: number
  projects: string[]
}

export type Report2Options = {
  reportDir: string
  phase1: Phase1Output
  phase2: Phase2Output
  meta: Report2Meta
}

/**
 * Write all three artifacts to reportDir (which must already exist):
 *   phase1.json  — raw observation output
 *   phase2.json  — raw rendering output
 *   report.md    — human-readable, joining items to observations by id
 */
export async function writeReport2(opts: Report2Options): Promise<void> {
  const { reportDir, phase1, phase2, meta } = opts

  await Promise.all([
    fs.writeFile(path.join(reportDir, 'phase1.json'), JSON.stringify(phase1, null, 2), 'utf-8'),
    fs.writeFile(path.join(reportDir, 'phase2.json'), JSON.stringify(phase2, null, 2), 'utf-8'),
    fs.writeFile(path.join(reportDir, 'report.md'), renderMarkdown(phase1, phase2, meta), 'utf-8'),
  ])
}

function renderMarkdown(phase1: Phase1Output, phase2: Phase2Output, meta: Report2Meta): string {
  const from = meta.start.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
  const to = meta.end.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })

  const obsById = new Map<string, Observation>(phase1.observations.map(o => [o.id, o]))

  const s: string[] = []

  s.push(`# Drift List — Session Analysis (Pipeline 2)`)
  s.push(`> ${from} → ${to} · ${meta.sessionCount} session${meta.sessionCount === 1 ? '' : 's'} · ${meta.projects.join(', ')}`)
  s.push('')

  if (phase1.observations.length === 0) {
    s.push(`## Observations`)
    s.push('')
    s.push('No unexamined decisions found in this window.')
    s.push('')
  } else {
    s.push(`## Observations & Exercises`)
    s.push('')

    for (const item of phase2.items) {
      const obs = obsById.get(item.id)

      if (obs) {
        s.push(`### ${obs.what_claude_did}`)
        s.push(`**What went unexamined:** ${obs.what_was_not_examined}`)
        s.push('')
        s.push(`**Evidence:** *${obs.evidence}*`)
        s.push('')
      }

      s.push(`**Why it matters:** ${item.why_it_matters}`)
      s.push('')

      if (item.exercise) {
        s.push(`**Exercise:** ${item.exercise}`)
      } else {
        s.push(`**Exercise:** *(omitted — ${item.omitted_because ?? 'no reason given'})*`)
      }
      s.push('')
    }
  }

  if (phase2.questions.length > 0) {
    s.push(`## Questions`)
    s.push('')
    for (let i = 0; i < phase2.questions.length; i++) {
      const q = phase2.questions[i]
      s.push(`**Q${i + 1}:** ${q.question}`)
      s.push('')
    }
  }

  s.push('---')
  s.push(`*Generated by drift-list (pipeline 2) · ${new Date().toISOString()}*`)

  return s.join('\n')
}
