import fs from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
import type { AnalysisResult } from './types.js'

const REPORTS_DIR = path.join(os.homedir(), '.drift-list', 'session-reports')

export type ReportOptions = {
  result: AnalysisResult
  outputPath?: string
}

/**
 * Write the analysis as a report folder:
 *   report-{timestamp}/
 *     report.md        — summary, watch list, arch questions
 *     analysis.json    — raw AnalysisResult (feeds future UI)
 *
 * Returns the path of the report directory.
 */
export async function writeReport(opts: ReportOptions): Promise<string> {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)
  const reportDir = opts.outputPath ?? path.join(REPORTS_DIR, `report-${timestamp}`)

  await fs.mkdir(reportDir, { recursive: true })

  await Promise.all([
    fs.writeFile(path.join(reportDir, 'report.md'), renderMarkdown(opts.result), 'utf-8'),
    fs.writeFile(path.join(reportDir, 'analysis.json'), JSON.stringify(opts.result, null, 2), 'utf-8'),
  ])

  return reportDir
}

function renderMarkdown(r: AnalysisResult): string {
  const { sessionWindow: sw } = r
  const from = new Date(sw.from).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
  const to = new Date(sw.to).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })

  const s: string[] = []

  s.push(`# Drift List — Session Analysis`)
  s.push(`> ${from} → ${to} · ${sw.sessionCount} session${sw.sessionCount === 1 ? '' : 's'} · ${sw.projects.join(', ')}`)
  s.push('')

  // Work categories
  s.push(`## Work Categories`)
  for (const cat of r.categories) {
    s.push(`- ${cat}`)
  }
  s.push('')

  // Skills in play
  s.push(`## Skills in Play`)
  for (const skill of r.skills) {
    s.push(`- ${skill}`)
  }
  s.push('')

  // Watch List — primary output
  s.push(`## Watch List — Where Claude Did the Driving`)
  s.push('')
  for (const item of r.watchList) {
    s.push(`### ${item.observation}`)
    s.push(`**Why it matters:** ${item.whyItMatters}`)
    s.push('')
    s.push(`**Micro-exercise:** ${item.microExercise}`)
    s.push('')
  }

  // Architectural Questions
  s.push(`## Architectural Questions`)
  s.push('')
  for (let i = 0; i < r.architecturalQuestions.length; i++) {
    const q = r.architecturalQuestions[i]
    s.push(`**Q${i + 1}: ${q.question}**`)
    s.push(`*${q.context}*`)
    s.push('')
  }

  s.push('---')
  s.push(`*Generated by drift-list · ${new Date().toISOString()}*`)

  return s.join('\n')
}
